### ISSUE TITLE
SMS Config open TODOs

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/sms-configuration-app#17]
Missing functionality:

* [x] Edit J2ME parser commands (@Mohammer5)
* [x] Edit Program Stage data entry parser commands (@Mohammer5)
* [x] Edit Alert parser commands (@ismay)
* [x] Edit Unregistered parser commands (@ismay) (https://github.com/dhis2/sms-configuration-app/pull/24)
* [x] Edit Tracked entity registration parser commands (@ismay)
* [ ] Edit Event registration parser commands (@Mohammer5)

Follow-up ToDos:

* [ ] Align wording
  * [ ] Inbound & outbound sms sections (#11)
* [ ] Abstract duplicate code
  * [ ] Edit KeyValue & J2ME parsers
* [ ] Improve stylings
  * [ ] Sms command edit forms
  * [ ] Gateway add/edit forms

Notes:

* [ ] Submitting an invalid Alert parser (without a user group), I'm getting back a 409, but that isn't handled, so the form stays stuck at `...submitting`
* [ ] After a successful sms command creation I would expect to be redirected to the sms commands overview
* [ ] Change `paging: 'false'` to `paging: false`
* [ ] Redirects after successful command creation aren't working

**Comment by ismay** [comment]
I'm assuming that `Edit Event registration parser commands` is done (it worked when I tested it). The follow-ups have been addressed mostly I think, and otherwise could be filed under the generic 'address tech debt' issue (#54). I checked the todo items under notes, and it seems like only the 'handle alert parser error' bug is still a thing, so I created a separate issue for that.

So I'll close this, but please let me know if anything else here is still an issue so that I can create a separate issue for it.
